package com.example.marcuraexchangeratebackend.insight.api;

import com.example.marcuraexchangeratebackend.insight.application.TrendInsightService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;

/**
 * REST controller for AI-powered trend insights.
 * <p>
 * Provides read-only access to AI-generated exchange rate trend analysis.
 * <p>
 * Does NOT increment usage counters.
 */
@RestController
@RequestMapping("/api/v1/exchange/insight")
@Tag(name = "AI Trend Insight", description = "AI-powered exchange rate trend analysis")
public class TrendInsightController {

    private final TrendInsightService trendInsightService;

    public TrendInsightController(TrendInsightService trendInsightService) {
        this.trendInsightService = trendInsightService;
    }

    /**
     * Generate an AI-powered trend insight for a currency pair within a date range.
     * <p>
     * Uses actual historical rate data stored locally (does NOT call Fixer.io).
     * <p>
     * Requires at least 2 historical data points for meaningful analysis.
     * <p>
     * Does NOT increment usage counters.
     *
     * @param from     source currency code (required, 3 letters)
     * @param to       target currency code (required, 3 letters)
     * @param fromDate start of date range (required, inclusive, ISO format)
     * @param toDate   end of date range (required, inclusive, ISO format)
     * @return AI-generated trend insight
     */
    @GetMapping
    @Operation(
            summary = "Get AI-powered trend insight",
            description = "Generates a concise natural-language trend insight for a currency pair " +
                    "using actual historical exchange rate data stored locally. " +
                    "The insight is generated by an AI model (Ollama/LLM) constrained to " +
                    "supplied data only, with no financial advice or invented causes. " +
                    "Requires at least 2 historical data points. " +
                    "Does NOT increment usage counters. " +
                    "Does NOT call Fixer.io.",
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "Trend insight generated successfully",
                            content = @Content(schema = @Schema(implementation = TrendInsightResponse.class))
                    ),
                    @ApiResponse(
                            responseCode = "400",
                            description = "Invalid request parameters (invalid currency, invalid date range, fromDate > toDate)"
                    ),
                    @ApiResponse(
                            responseCode = "404",
                            description = "No historical rate data available in the selected period"
                    ),
                    @ApiResponse(
                            responseCode = "503",
                            description = "AI provider (Ollama/LLM) is unavailable or failed"
                    )
            }
    )
    public ResponseEntity<TrendInsightResponse> getTrendInsight(
            @Parameter(description = "Source currency code (3 letters)", example = "EUR", required = true)
            @RequestParam @Pattern(regexp = "^\\s*[A-Za-z]{3}\\s*$") @NotNull String from,

            @Parameter(description = "Target currency code (3 letters)", example = "GBP", required = true)
            @RequestParam @Pattern(regexp = "^\\s*[A-Za-z]{3}\\s*$") @NotNull String to,

            @Parameter(description = "Start of date range (inclusive, ISO format)", example = "2024-02-01", required = true)
            @RequestParam @NotNull @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate fromDate,

            @Parameter(description = "End of date range (inclusive, ISO format)", example = "2024-03-01", required = true)
            @RequestParam @NotNull @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate toDate
    ) {
        String insight = trendInsightService.generateTrendInsight(from, to, fromDate, toDate);

        TrendInsightResponse response = new TrendInsightResponse(
                from,
                to,
                fromDate,
                toDate,
                insight
        );

        return ResponseEntity.ok(response);
    }
}
